# Advanced Data Analytics Pipeline Configuration
# Professional configuration for comprehensive business intelligence platform
# Author: Osman Abdullahi

# Application Settings
app:
  name: "Advanced Data Analytics Pipeline"
  version: "1.0.0"
  author: "Osman Abdullahi"
  email: "Osmandabdullahi@gmail.com"
  description: "Professional data analytics platform for business intelligence"

# Data Sources Configuration
data_sources:
  sales:
    file_path: "data/sales_data.csv"
    date_column: "date"
    customer_column: "customer_id"
    revenue_column: "revenue"
    description: "Sales transaction data with customer demographics"
    
  financial:
    file_path: "data/financial_data.csv"
    date_column: "date"
    symbol_column: "symbol"
    price_column: "close"
    description: "Financial market data for portfolio analysis"
    
  ecommerce:
    file_path: "data/ecommerce_data.csv"
    date_column: "date"
    user_column: "user_id"
    revenue_column: "revenue"
    description: "E-commerce user behavior and conversion data"

# Statistical Analysis Configuration
statistical_analysis:
  confidence_level: 0.95
  correlation_methods: ["pearson", "spearman", "kendall"]
  hypothesis_tests:
    - "ttest"
    - "anova"
    - "mannwhitney"
    - "kruskal"
  outlier_detection:
    method: "iqr"
    threshold: 1.5

# Business Intelligence Configuration
business_intelligence:
  kpi_metrics:
    - "total_revenue"
    - "customer_count"
    - "avg_order_value"
    - "customer_retention_rate"
    - "revenue_growth_rate"
  
  reporting_periods:
    - "daily"
    - "weekly"
    - "monthly"
    - "quarterly"
    
  revenue_analysis:
    growth_calculation: "period_over_period"
    seasonality_adjustment: true
    trend_analysis: true
    
  customer_analysis:
    ltv_calculation: true
    cohort_analysis: true
    churn_prediction: true

# Machine Learning Configuration
machine_learning:
  customer_segmentation:
    methods:
      rfm:
        recency_weight: 1.0
        frequency_weight: 1.0
        monetary_weight: 1.0
        score_range: [1, 5]
      
      kmeans:
        n_clusters: "auto"  # or specific number
        max_clusters: 8
        random_state: 42
        
      dbscan:
        eps: 0.5
        min_samples: 5
        
  predictive_models:
    churn_prediction:
      algorithm: "random_forest"
      features: ["recency", "frequency", "monetary", "tenure"]
      test_size: 0.2
      
    sales_forecasting:
      method: "arima"
      seasonal_periods: 12
      confidence_interval: 0.95

# Visualization Configuration
visualization:
  style: "seaborn"
  color_palette: "husl"
  figure_size: [12, 8]
  dpi: 300
  
  dashboard:
    theme: "bootstrap"
    refresh_interval: 30  # seconds
    auto_update: true
    
  charts:
    revenue_trend:
      type: "line"
      smoothing: true
      
    customer_segments:
      type: "pie"
      show_percentages: true
      
    correlation_matrix:
      type: "heatmap"
      annotation: true

# Reporting Configuration
reporting:
  output_formats: ["pdf", "html", "markdown"]
  template_directory: "templates/"
  
  executive_summary:
    include_kpis: true
    include_trends: true
    include_recommendations: true
    max_pages: 5
    
  technical_report:
    include_methodology: true
    include_code: false
    include_raw_data: false
    statistical_details: true
    
  comprehensive_report:
    include_all_analyses: true
    include_visualizations: true
    include_appendix: true

# Dashboard Configuration
dashboard:
  host: "0.0.0.0"
  port: 8050
  debug: false
  
  layout:
    header:
      title: "Executive Analytics Dashboard"
      subtitle: "Advanced Data Analytics Portfolio - Osman Abdullahi"
      
    kpi_cards:
      - "total_revenue"
      - "customer_count"
      - "avg_order_value"
      - "customer_satisfaction"
      
    charts:
      - name: "revenue_trend"
        position: [0, 0]
        size: [6, 4]
        
      - name: "customer_segments"
        position: [6, 0]
        size: [6, 4]
        
      - name: "channel_performance"
        position: [0, 4]
        size: [6, 4]
        
      - name: "financial_performance"
        position: [6, 4]
        size: [6, 4]

# Data Quality Configuration
data_quality:
  validation_rules:
    completeness:
      threshold: 0.95  # 95% completeness required
      
    consistency:
      date_format: "%Y-%m-%d"
      currency_format: "USD"
      
    accuracy:
      revenue_range: [0, 1000000]
      age_range: [18, 100]
      
  cleansing:
    remove_duplicates: true
    handle_missing_values: "interpolate"
    outlier_treatment: "cap"

# Performance Configuration
performance:
  caching:
    enabled: true
    ttl: 3600  # 1 hour
    
  parallel_processing:
    enabled: true
    max_workers: 4
    
  memory_optimization:
    chunk_size: 10000
    use_categorical: true

# Security Configuration
security:
  data_anonymization:
    enabled: false
    pii_columns: ["customer_id", "email", "phone"]
    
  access_control:
    require_authentication: false
    allowed_ips: ["127.0.0.1", "localhost"]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      
    file:
      enabled: true
      level: "DEBUG"
      filename: "logs/analytics.log"
      max_size: "10MB"
      backup_count: 5

# Integration Configuration
integrations:
  databases:
    postgresql:
      enabled: false
      host: "localhost"
      port: 5432
      database: "analytics"
      
    mongodb:
      enabled: false
      host: "localhost"
      port: 27017
      database: "analytics"
      
  cloud_services:
    aws:
      enabled: false
      region: "us-east-1"
      
    gcp:
      enabled: false
      project_id: "analytics-project"
      
  apis:
    external_data:
      enabled: false
      rate_limit: 100  # requests per minute
